### ISSUE TITLE
[FreeBSD] all commands fail

### ISSUE THREAD

**Issue by dijit** [ok-borg/borg#57]
Systeminfo: 
`uname: FreeBSD heap.of.shit.<DOMAIN> 11.0-RELEASE-p2 FreeBSD 11.0-RELEASE-p2 #0: Mon Oct 24 06:55:27 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64`

`go version go1.8 freebsd/amd64`

No matter what command I try to run I am presented with the following:

```
panic: user: Current not implemented on freebsd/amd64

goroutine 1 [running]:
github.com/crufter/borg/conf.init.1()
	/Users/crufter/go/src/github.com/crufter/borg/conf/conf.go:36 +0x62
github.com/crufter/borg/conf.init()
	/Users/crufter/go/src/github.com/crufter/borg/conf/conf.go:72 +0x1e8
github.com/crufter/borg/commands.init()
	/Users/crufter/go/src/github.com/crufter/borg/commands/worked.go:80 +0x4a
main.init()
	/Users/crufter/go/src/github.com/crufter/borg/main.go:39 +0x40
heap ~/Downloads » borg worked 12                                                            2 ↵
panic: user: Current not implemented on freebsd/amd64

goroutine 1 [running]:
github.com/crufter/borg/conf.init.1()
	/Users/crufter/go/src/github.com/crufter/borg/conf/conf.go:36 +0x62
github.com/crufter/borg/conf.init()
	/Users/crufter/go/src/github.com/crufter/borg/conf/conf.go:72 +0x1e8
github.com/crufter/borg/commands.init()
	/Users/crufter/go/src/github.com/crufter/borg/commands/worked.go:80 +0x4a
main.init()
	/Users/crufter/go/src/github.com/crufter/borg/main.go:39 +0x40
```

My installation was;
```bash
wget https://github.com/ok-borg/borg/releases/download/v0.0.2/borg_freebsd_amd64 -O /usr/local/bin/borg
chmod 755 /usr/local/bin/borg
```

**Comment by crufter** [comment]
Yes, this is a really annoying thing one of the go packages uses unavailable dependencies on some systems. We are going to fix this first thing!

Sorry about this @dijit

**Comment by crufter** [comment]
This should be fixed now @dijit
